### ISSUE TITLE
Check for good projects on NPM

### ISSUE THREAD

**Issue by koltyakov** [SharePoint-NodeJS/Awesome-SharePoint-Node.js#1]
Check for good projects on NPM https://www.npmjs.com/browse/keyword/sharepoint.
Add references in the list.

**Comment by koltyakov** [comment]
> Ignoring modules which have not been updated for years.

## These guys should be definitely mentioned in the list:
- [ ] https://github.com/vman/spfx-extensions-cli - CLI tool to view spfx extensions currently installed on your sitecollection, site or a list
- [ ] sp-pnp-js - not for Node.js as is but can be easily executed in Node.js and a super useful library
- [ ] gd-sprest - REST wrapper, similar to sp-pnp-js
- [ ] gulp-spcolor2scss - Convert SharePoint spcolor-files to Sass partials
- [ ] gulp-spsync - Gulp plugin for synchronizing local files with a SharePoint library
- [ ] spscript - yet another REST API wrapper
- [ ] gulp-spsync-creds - Gulp plugin for synchronizing local files with a SharePoint library
- [ ] node-sppkg-deploy - automating the deployment process of SharePoint application packages in the App Catalog site
- [ ] generator-displaytemplates - Yeoman generator that gives you a kick start for building Search Display Templates
- [ ] CSOMNode - JSOM polyfill for Node.js environment

## To investigate:

- [ ] sharepointconnector
- [ ] spbones
- [ ] spfxhelper 

[Still working on this, any suggestions are welcome]

**Comment by koltyakov** [comment]
https://github.com/vman/spfx-extentions-cli - CLI tool to view spfx extensions currently installed on your sitecollection, site or a list

**Comment by s-KaiNet** [comment]
#4 for current list and state

**Comment by koltyakov** [comment]
Very robust criterias, agree on them.

**Comment by s-KaiNet** [comment]
Please refer to new a criteria in #4  :) 
I'll remove from current list.
