### ISSUE TITLE
AADSTS50058: A silent sign-in request was sent but no user is signed in

### ISSUE THREAD

**Issue by anfasci** [SharePoint-NodeJS/Awesome-SharePoint-Node.js#21]
StatusCodeError: 400 - "{"error":"invalid_grant","error_description":"AADSTS50058: A silent sign-in request was sent but no user is signed in.\r\nTrace ID: 05db5c6a-155c-4870-9bca-a518b5931900\r\nCorrelation ID: 1e8372d0-c1ba-4070-88d7-597e9cb5cb2c\r\nTimestamp: 2019-08-14 12:04:42Z","error_codes":[50058],"timestamp":"2019-08-14 12:04:42Z","trace_id":"05db5c6a-155c-4870-9bca-a518b5931900","correlation_id":"1e8372d0-c1ba-4070-88d7-597e9cb5cb2c","error_uri":"https://login.microsoftonline.com/error?code=50058\"}"

URL= 'https://login.microsoftonline.com/' + process.env.TENANT_ID + '/oauth2/token',

I am trying to implement azure login in nodejs scheduler app, and then want to upload file to sharepoint.
First i need to login, then get accesstoken,refresh token, admin accesstoken etc.
When i try to get accesstoken , i got error like this.
Can you help me.
Here no use of any front end.

async function init(parsedBody) {
  var jwtToken = await sharepointAuth.getJWTToken(parsedBody);
  console.log("jwtToken:",jwtToken)
  const config = {
    JWK_URI: appConstants.JWK_URI,
    ISS: appConstants.ISS,
    AUD: appConstants.conf.AUD,
  };
  console.log(config)
  await azureJWT.verify(jwtToken, config).then(async () => {
    console.log("----------------------------------")
    var fileName = 'analytics.min.js';
    var filePath = './public/analytics.min.js';
    var userAccessToken = await sharepointAuth.getAccessToken(jwtToken);
    console.log("userAccessToken:", userAccessToken);
    var accessTokenObj = await sharepointAuth.getAdminAccessToken();
    accessToken = accessTokenObj.access_token;
    console.log("accessToken:", accessToken)
    fs.readFile(filePath, { encoding: null }, function (err, data) {
      const relativeUrl = `web/GetFolderByServerRelativeUrl('${selectedFolderName}')`;
      const SHAREPOINT_HEADER = {
        'Authorization': `Bearer ${accessToken}`,
        "Content-Type": `application/json;odata=verbose`,
        'Accept': 'application/json;odata=verbose',
      }
      const options = {
        method: "POST",
        uri: `${SHAREPOINT_URI}${relativeUrl}/Files/add(url='${fileName}',overwrite=true)`,
        headers: SHAREPOINT_HEADER,
        body: data
      };
      console.log(options)
      rp(options)
        .then(() => {
          // POST succeeded...
          console.log('File uploaded!');
        })
        .catch((error) => {
          // POST failed...
          console.log("File Upload Error: ", error.toString());
        });
    });
  });
}
const request = require("request");
const endpoint = "https://login.microsoftonline.com/tenentId/oauth2/token";
const requestParams = {
  grant_type: "client_credentials",
  client_id: "ClientId",
  client_secret: "Secret",
  resource: "ClientId"
};

request.post({ url: endpoint, form: requestParams }, function (err, response, body) {
  if (err) {
    console.log("error");
  }
  else {
    console.log("Body=" + body);
    let parsedBody = JSON.parse(body);
    if (parsedBody.error_description) {
      console.log("Error=" + parsedBody.error_description);
    }
    else {
      console.log("parsedBody :    " + parsedBody);
      console.log("Access Token=" + parsedBody.access_token);
      init(parsedBody);
    }
  }
});

**Comment by koltyakov** [comment]
It’s not a forum, but tools and libraries collection reference.
