### ISSUE TITLE
How about adding total downloads badge?

### ISSUE THREAD

**Issue by koltyakov** [SharePoint-NodeJS/Awesome-SharePoint-Node.js#9]
E.g.: [![Total Downloads](https://img.shields.io/npm/dt/node-sp-auth.svg)](https://www.npmjs.com/package/node-sp-auth)

**Comment by s-KaiNet** [comment]
Good, why not    
A lot of manual updates of readme though :)

**Comment by koltyakov** [comment]
I have an idea, how to semi-automate the thing.
Let me just do it =)

**Comment by koltyakov** [comment]
Have applied some automation.
